repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      #      - id: poetry-lock
      - id: poetry-export
        args: [ "--without-hashes", "--dev", "-f", "requirements.txt", "-o", "requirements.txt" ]
