# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 .
      - name: Test with pytest
        run: |
          pipenv run pytest libpythonpro --cov=libpythonpro
      - name: Posting Coverage
        env:
          CODECOV_TOKEN: "843d0e48-24be-4fe6-b002-2178212cd800"
        run: |
          sudo pip install codecov
          pipenv run codecov
